CREATE TABLE IF NOT EXISTS department (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT    NOT NULL UNIQUE,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_user (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT    NOT NULL,
    employee_no  TEXT    NOT NULL UNIQUE,
    department   TEXT    NOT NULL,
    position     TEXT    NOT NULL DEFAULT '',
    level        TEXT    NOT NULL,
    phone        TEXT    NOT NULL,
    id_card_tail TEXT    NOT NULL,
    password     TEXT    NOT NULL,
    status       TEXT    NOT NULL DEFAULT 'active',
    is_admin     INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(phone, id_card_tail)
);

CREATE TABLE IF NOT EXISTS division_leader_department (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    department    TEXT    NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, department)
);

CREATE TABLE IF NOT EXISTS batch (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT    NOT NULL,
    period          TEXT    NOT NULL DEFAULT '',
    start_time      TEXT    NOT NULL,
    end_time        TEXT    NOT NULL,
    status          TEXT    NOT NULL DEFAULT 'draft',
    peer_cross_dept INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eval_matrix (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id   INTEGER NOT NULL REFERENCES batch(id) ON DELETE CASCADE,
    from_role  TEXT    NOT NULL,
    to_role    TEXT    NOT NULL,
    eval_type  TEXT    NOT NULL,
    enabled    INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS relation (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id     INTEGER NOT NULL REFERENCES batch(id) ON DELETE CASCADE,
    evaluator_id INTEGER NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    target_id    INTEGER NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    role_type    TEXT    NOT NULL,
    eval_type    TEXT    NOT NULL,
    status       TEXT    NOT NULL DEFAULT 'pending',
    is_anonymous INTEGER NOT NULL DEFAULT 1,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS self_question (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    INTEGER NOT NULL REFERENCES batch(id) ON DELETE CASCADE,
    user_id     INTEGER NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    content_1   TEXT,
    content_2   TEXT,
    content_3   TEXT,
    content_4   TEXT,
    content_5   TEXT,
    content_6   TEXT,
    content_7   TEXT,
    content_8   TEXT,
    content_9   TEXT,
    content_10  TEXT,
    weight_1    REAL,
    weight_2    REAL,
    weight_3    REAL,
    weight_4    REAL,
    weight_5    REAL,
    weight_6    REAL,
    weight_7    REAL,
    weight_8    REAL,
    weight_9    REAL,
    weight_10   REAL,
    comp_content_1 TEXT,
    comp_content_2 TEXT,
    comp_content_3 TEXT,
    comp_content_4 TEXT,
    comp_content_5 TEXT,
    comp_weight_1  REAL,
    comp_weight_2  REAL,
    comp_weight_3  REAL,
    comp_weight_4  REAL,
    comp_weight_5  REAL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(batch_id, user_id)
);

CREATE TABLE IF NOT EXISTS answer (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id INTEGER NOT NULL REFERENCES relation(id) ON DELETE CASCADE,
    question_seq INTEGER,
    score       REAL,
    is_total    INTEGER NOT NULL DEFAULT 0,
    is_draft    INTEGER NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(relation_id, question_seq)
);

CREATE TABLE IF NOT EXISTS log (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER REFERENCES app_user(id) ON DELETE SET NULL,
    action     TEXT    NOT NULL,
    ip         TEXT,
    detail     TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_phone_idcard ON app_user(phone, id_card_tail);
CREATE INDEX IF NOT EXISTS idx_app_user_level_status_department ON app_user(level, status, department);
CREATE INDEX IF NOT EXISTS idx_app_user_employee_no ON app_user(employee_no);
CREATE INDEX IF NOT EXISTS idx_department_sort_id ON department(sort_order, id);
CREATE INDEX IF NOT EXISTS idx_relation_batch_evaluator ON relation(batch_id, evaluator_id);
CREATE INDEX IF NOT EXISTS idx_relation_batch_evaluator_type ON relation(batch_id, evaluator_id, eval_type);
CREATE INDEX IF NOT EXISTS idx_relation_batch_target ON relation(batch_id, target_id);
CREATE INDEX IF NOT EXISTS idx_relation_batch_target_type ON relation(batch_id, target_id, eval_type);
CREATE INDEX IF NOT EXISTS idx_relation_batch_status ON relation(batch_id, status);
CREATE INDEX IF NOT EXISTS idx_relation_batch_type_status ON relation(batch_id, eval_type, status);
CREATE INDEX IF NOT EXISTS idx_answer_relation ON answer(relation_id);
CREATE INDEX IF NOT EXISTS idx_answer_relation_total ON answer(relation_id, is_total);
CREATE INDEX IF NOT EXISTS idx_self_question_batch ON self_question(batch_id);
CREATE INDEX IF NOT EXISTS idx_self_question_user ON self_question(user_id);
CREATE INDEX IF NOT EXISTS idx_self_question_batch_user ON self_question(batch_id, user_id);
CREATE INDEX IF NOT EXISTS idx_log_user ON log(user_id);
CREATE INDEX IF NOT EXISTS idx_log_created ON log(created_at);
